# This user is required for the unit tests to work. Change the parameters according to your own test user
TEST_USER:
  id: 347980
  s_number: "s9999999"
  first_name: "Test"

# This user has not signed their SDD mandate
TEST_USER_NO_SDD:
  id: 485567
  s_number: "s9999998"
  first_name: "TestTwee"

# Folder ID for the folder which contains the test
TEST_FOLDER_ID: 1998

# This item is required for the unit tests to work. Change the parameters according to your own test item
TEST_ITEM:
  id: 13591
  folder_id: 1998
  name: "Testproduct"




